name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build windows x64
        run: CGO_ENABLED=0 GOOS="windows" GOARCH="amd64" go build -o ./build/hd2k-win-x64.exe ./cmd/hd2-killer/run.go

      - name: Upload windows x64
        uses: actions/upload-artifact@v4
        with:
          name: hd2k-win-x64.exe
          path: ./build/hd2k-win-x64.exe
